export const role_name: RoleName = {
    carrier: 'carrier',
    remote_carry: 'remote_carry',
    harvester: 'harvester',
    remote_harvester: 'remote_harvester',
    remote_reserve: 'remote_reserve',
    remote_builder: 'remote_builder',
    remote_attack: 'remote_attack',
    claim_start: 'claim_start',
    remote_repair: 'remote_repair',
    starter: 'starter',
    upgrader: 'upgrader',
    builder: 'builder',
    scout: 'scout',
    claim: 'claim',
    repair: 'repair',
    attack: 'attack',
    heal: 'heal',
    upg: 'upg',
};
global.w_role_name = role_name;
